name: Build and push on main branch

on:
  push:
    branches:
      - "*"
      - "!master"
      - "!main'"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and tag Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}
          push: true
          tags: registry.digitalocean.com/tht/vex-reactjs-frontend:latest_dev
